# Generated by Django 2.0.4 on 2018-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevInfoVerbose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysDescr', models.CharField(max_length=1024)),
                ('errorInfo', models.CharField(max_length=1024)),
                ('IP', models.CharField(max_length=16)),
                ('sysUptime', models.CharField(max_length=128)),
                ('sysContact', models.CharField(max_length=512)),
                ('sysName', models.CharField(max_length=128)),
                ('sysLocation', models.CharField(max_length=512)),
                ('hardwareVersion', models.CharField(max_length=512)),
                ('softwareVersion', models.CharField(max_length=512)),
                ('serialNumber', models.CharField(max_length=128)),
                ('CPUUsage', models.CharField(max_length=32)),
                ('CPUUsageUpper', models.CharField(max_length=32)),
                ('memoryUsage', models.CharField(max_length=32)),
                ('memoryUsageUpper', models.CharField(max_length=32)),
                ('memorySize', models.CharField(max_length=128)),
                ('CPUTemprature', models.CharField(max_length=32)),
                ('CPUTempratureUpper', models.CharField(max_length=32)),
                ('CPUTempratureLower', models.CharField(max_length=32)),
                ('ARPTable', models.CharField(max_length=2048)),
                ('MAC', models.CharField(max_length=32)),
                ('MACTable', models.CharField(max_length=2048)),
                ('UpLinkPort', models.CharField(max_length=32)),
            ],
        ),
    ]
